# Generated by Django 4.2.4 on 2023-09-23 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="visitor",
            old_name="v_contact",
            new_name="contact",
        ),
        migrations.RenameField(
            model_name="visitor",
            old_name="v_name",
            new_name="name",
        ),
        migrations.RemoveField(
            model_name="visitor",
            name="user",
        ),
    ]
